---
Organizations:
  - &OrdererOrg
    Name: OrdererMSP
    ID: OrdererMSP
    MSPDir: ../crypto-config/ordererOrganizations/treasury.gov/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
  - &Treasury
    Name: TreasuryMSP
    ID: TreasuryMSP
    MSPDir: ../crypto-config/peerOrganizations/treasury.gov/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('TreasuryMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('TreasuryMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('TreasuryMSP.admin')"
  - &HHS
    Name: HHSMSP
    ID: HHSMSP
    MSPDir: ../crypto-config/peerOrganizations/hhs.gov/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('HHSMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('HHSMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('HHSMSP.admin')"
  - &DoD
    Name: DoDMSP
    ID: DoDMSP
    MSPDir: ../crypto-config/peerOrganizations/dod.gov/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('DoDMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('DoDMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('DoDMSP.admin')"
  - &Education
    Name: EducationMSP
    ID: EducationMSP
    MSPDir: ../crypto-config/peerOrganizations/ed.gov/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('EducationMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('EducationMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('EducationMSP.admin')"
  - &SSA
    Name: SSAMSP
    ID: SSAMSP
    MSPDir: ../crypto-config/peerOrganizations/ssa.gov/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('SSAMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('SSAMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('SSAMSP.admin')"
  - &IRS
    Name: IRSMSP
    ID: IRSMSP
    MSPDir: ../crypto-config/peerOrganizations/irs.gov/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('IRSMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('IRSMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('IRSMSP.admin')"
  - &DOT
    Name: DOTMSP
    ID: DOTMSP
    MSPDir: ../crypto-config/peerOrganizations/dot.gov/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('DOTMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('DOTMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('DOTMSP.admin')"

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer.treasury.gov:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
    - *OrdererOrg
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:  # Added here
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Capabilities:
    <<: *OrdererCapabilities

Application: &ApplicationDefaults
  Organizations:
    - *Treasury
    - *HHS
    - *DoD
    - *Education
    - *SSA
    - *IRS
    - *DOT
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ApplicationCapabilities

Profiles:
  Genesis:
    Policies:
      Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
      Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
      Admins:
        Type: ImplicitMeta
        Rule: "MAJORITY Admins"
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"
        Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"
        Admins:
          Type: ImplicitMeta
          Rule: "MAJORITY Admins"
        BlockValidation:  # Added here
          Type: ImplicitMeta
          Rule: "ANY Writers"
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      FederalConsortium:
        Organizations:
          - *Treasury
          - *HHS
          - *DoD
          - *Education
          - *SSA
          - *IRS
          - *DOT
  TreasuryChannel:
    Consortium: FederalConsortium
    Policies:
      Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
      Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
      Admins:
        Type: ImplicitMeta
        Rule: "MAJORITY Admins"
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Treasury
        - *HHS
        - *DoD
        - *Education
        - *SSA
        - *IRS
        - *DOT
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"
        Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"
        Admins:
          Type: ImplicitMeta
          Rule: "MAJORITY Admins"
      Capabilities:
        <<: *ApplicationCapabilities
    Capabilities:
      <<: *ChannelCapabilities