networks:
  basic:

services:
  ca.treasury.gov:
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.treasury.gov
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.treasury.gov-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/treasury.gov/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.treasury.gov
    networks:
      - basic

  orderer.treasury.gov:
    image: hyperledger/fabric-orderer:2.2.0
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    ports:
      - 7050:7050
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/treasury.gov/orderers/orderer.treasury.gov/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/treasury.gov/orderers/orderer.treasury.gov/tls:/var/hyperledger/orderer/tls
    container_name: orderer.treasury.gov
    networks:
      - basic

  peer0.treasury.gov:
    container_name: peer0.treasury.gov
    image: hyperledger/fabric-peer:2.2.0
    environment:
      - CORE_PEER_ID=peer0.treasury.gov
      - CORE_PEER_ADDRESS=peer0.treasury.gov:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.treasury.gov:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.treasury.gov:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.treasury.gov:7051
      - CORE_PEER_LOCALMSPID=TreasuryMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    ports:
      - 7051:7051
    volumes:
      - ./crypto-config/peerOrganizations/treasury.gov/peers/peer0.treasury.gov/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/treasury.gov/peers/peer0.treasury.gov/tls:/etc/hyperledger/fabric/tls
    networks:
      - basic

  peer0.transportation.gov:
    container_name: peer0.transportation.gov
    image: hyperledger/fabric-peer:2.2.0
    environment:
      - CORE_PEER_ID=peer0.transportation.gov
      - CORE_PEER_ADDRESS=peer0.transportation.gov:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.transportation.gov:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.transportation.gov:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.transportation.gov:8051
      - CORE_PEER_LOCALMSPID=TransportationMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    ports:
      - 8051:8051
    volumes:
      - ./crypto-config/peerOrganizations/transportation.gov/peers/peer0.transportation.gov/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/transportation.gov/peers/peer0.transportation.gov/tls:/etc/hyperledger/fabric/tls
    networks:
      - basic

  peer0.education.gov:
    container_name: peer0.education.gov
    image: hyperledger/fabric-peer:2.2.0
    environment:
      - CORE_PEER_ID=peer0.education.gov
      - CORE_PEER_ADDRESS=peer0.education.gov:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.education.gov:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.education.gov:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.education.gov:9051
      - CORE_PEER_LOCALMSPID=EducationMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    ports:
      - 9051:9051
    volumes:
      - ./crypto-config/peerOrganizations/education.gov/peers/peer0.education.gov/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/education.gov/peers/peer0.education.gov/tls:/etc/hyperledger/fabric/tls
    networks:
      - basic

  peer0.defense.gov:
    container_name: peer0.defense.gov
    image: hyperledger/fabric-peer:2.2.0
    environment:
      - CORE_PEER_ID=peer0.defense.gov
      - CORE_PEER_ADDRESS=peer0.defense.gov:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer0.defense.gov:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.defense.gov:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.defense.gov:10051
      - CORE_PEER_LOCALMSPID=DefenseMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    ports:
      - 10051:10051
    volumes:
      - ./crypto-config/peerOrganizations/defense.gov/peers/peer0.defense.gov/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/defense.gov/peers/peer0.defense.gov/tls:/etc/hyperledger/fabric/tls
    networks:
      - basic

  peer0.aviation.gov:
    container_name: peer0.aviation.gov
    image: hyperledger/fabric-peer:2.2.0
    environment:
      - CORE_PEER_ID=peer0.aviation.gov
      - CORE_PEER_ADDRESS=peer0.aviation.gov:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.aviation.gov:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.aviation.gov:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.aviation.gov:11051
      - CORE_PEER_LOCALMSPID=AviationMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    ports:
      - 11051:11051
    volumes:
      - ./crypto-config/peerOrganizations/aviation.gov/peers/peer0.aviation.gov/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/aviation.gov/peers/peer0.aviation.gov/tls:/etc/hyperledger/fabric/tls
    networks:
      - basic

  peer0.biodiversity.gov:
    container_name: peer0.biodiversity.gov
    image: hyperledger/fabric-peer:2.2.0
    environment:
      - CORE_PEER_ID=peer0.biodiversity.gov
      - CORE_PEER_ADDRESS=peer0.biodiversity.gov:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer0.biodiversity.gov:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.biodiversity.gov:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.biodiversity.gov:12051
      - CORE_PEER_LOCALMSPID=BioDiversityMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    ports:
      - 12051:12051
    volumes:
      - ./crypto-config/peerOrganizations/biodiversity.gov/peers/peer0.biodiversity.gov/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/biodiversity.gov/peers/peer0.biodiversity.gov/tls:/etc/hyperledger/fabric/tls
    networks:
      - basic

  peer0.externalaffairs.gov:
    container_name: peer0.externalaffairs.gov
    image: hyperledger/fabric-peer:2.2.0
    environment:
      - CORE_PEER_ID=peer0.externalaffairs.gov
      - CORE_PEER_ADDRESS=peer0.externalaffairs.gov:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer0.externalaffairs.gov:13052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.externalaffairs.gov:13051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.externalaffairs.gov:13051
      - CORE_PEER_LOCALMSPID=ExternalAffairsMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    ports:
      - 13051:13051
    volumes:
      - ./crypto-config/peerOrganizations/externalaffairs.gov/peers/peer0.externalaffairs.gov/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/externalaffairs.gov/peers/peer0.externalaffairs.gov/tls:/etc/hyperledger/fabric/tls
    networks:
      - basic

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.2.0
    tty: true
    stdin_open: true
    environment:
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.treasury.gov:7051
      - CORE_PEER_LOCALMSPID=TreasuryMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/crypto-config/peerOrganizations/treasury.gov/peers/peer0.treasury.gov/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/crypto-config/peerOrganizations/treasury.gov/peers/peer0.treasury.gov/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/crypto-config/peerOrganizations/treasury.gov/peers/peer0.treasury.gov/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/crypto-config/peerOrganizations/treasury.gov/users/Admin@treasury.gov/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - ./crypto-config:/etc/hyperledger/fabric/crypto-config
      - ./channel-artifacts:/etc/hyperledger/fabric/channel-artifacts
      - ./chaincode:/opt/gopath/src/github.com/hyperledger/fabric/chaincode
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - basic